cart/urls.py
from django.urls import path
from . import views
from django.views.generic import RedirectView 

app_name = 'cart'

urlpatterns = [
    
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),

    path('index/', RedirectView.as_view(url='/index', permanent=False)),
    path('product/', RedirectView.as_view(url='/product', permanent=False)),
    path('blog/', RedirectView.as_view(url='/blog', permanent=False)),
    path('about/', RedirectView.as_view(url='/about', permanent=False)),
    path('contact/', RedirectView.as_view(url='/contact', permanent=False)),
    path('login/', RedirectView.as_view(url='/login', permanent=False)),
    path('register/', RedirectView.as_view(url='/register', permanent=False)),
    path('cart/', RedirectView.as_view(url='/cart', permanent=False)),
    path('checkout/', RedirectView.as_view(url='/checkout', permanent=False)),
    path('product-single/', RedirectView.as_view(url='/product-single', permanent=False)),
]

liquid/urls.py
from django.contrib import admin
from account.views import PasswordChangeView
from django.urls import include, path
from django.conf.urls.static import static
from account.views import aboutView, accountView, blogView, blogsingleView, checkoutView, contactView, faqView, productView, productsingleView, register, socialbackenderView, user_login
from liquid import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', accountView, name="index"),
    path('index', accountView, name="index"),
    path('about', aboutView, name="about"),
    path('blog', blogView, name="blog"),
    path('contact', contactView, name="contact"),
    path('product', productView, name="product"),
    path('product-single', productsingleView, name="product-single"),
    path('checkout', checkoutView, name="checkout"),
    path('social-backender', socialbackenderView, name="social-backender"),
    path('blog-single', blogsingleView, name="blog-single"),
    path('faq', faqView, name="faq"),
    path('cart/', include('cart.urls', namespace='cart')),
    # path('', include('django.contrib.auth.urls')),

    path('login/', user_login, name='login'),
    path('register/', register, name='register'),
    path('password-change/', PasswordChangeView.as_view(), name='password-change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),



]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

about/models.py
from django.db import models


class About(models.Model):
    title = models.CharField(max_length=125)
    content = models.CharField(max_length=225)
    image = models.ImageField(null=True, blank=True)
    since = models.IntegerField()
    experience = models.IntegerField()

    class Meta:
        verbose_name = "about"
        verbose_name_plural = "abouts"

    def __str__(self):
        return self.title


class Liquid(models.Model):
    name = models.CharField(max_length=125)
    image = models.ImageField(null=True, blank=True)

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=125)
    content = models.CharField(max_length=125)
    image = models.ImageField(null=True, blank=True)
    date = models.DateField(null=True, blank=True)
    link = models.CharField(max_length=125, null=True, blank=True)

    class Meta:
        verbose_name = "blog"
        verbose_name_plural = "blogs"

    def __str__(self):
        return self.title

cart/models.py
from django.db import models

# Create your models here.

checkout/models.py
from django.db import models


class Checkout(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    street_address = models.CharField(max_length=255)
    apartment = models.CharField(max_length=255, blank=True)
    city = models.CharField(max_length=100)
    postcode = models.CharField(max_length=20)
    phone = models.CharField(max_length=20)
    email = models.EmailField()
    create_account = models.BooleanField(default=False)
    different_address = models.BooleanField(default=False)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    discount = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    product_names = models.TextField(blank=True, null=True)  # Use TextField for potentially long strings
    quantities = models.TextField(blank=True, null=True)

    class Meta:
        verbose_name = "checkout"
        verbose_name_plural = "checkouts"

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

contact/models.py
from django.db import models
from django.core.validators import validate_email

class Contactus(models.Model):
    name = models.CharField(max_length=128)
    email = models.EmailField(
                              validators=[validate_email])
    subject = models.CharField(max_length=15,blank=True,null=True)
    message = models.TextField()

    class Meta:
        verbose_name = "contactus"
        verbose_name_plural = "contactsus"

    def __str__(self):
        return self.name
    
class Company(models.Model):
    address = models.CharField(max_length=225)    
    phone = models.IntegerField()    
    email = models.EmailField(max_length=225)    
    website = models.CharField(max_length=225)   

    class Meta:
        verbose_name = "Company"
        verbose_name_plural = "Company"

    def __str__(self):
        return self.email 

faq/models.py
from django.db import models
from django.utils import timezone


class Faq(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'
        
    title = models.CharField(max_length=125)
    slug = models.SlugField(max_length=125)
    content = models.TextField(null=True, blank=True) 
    link = models.CharField(max_length=125, null=True, blank=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "faq"
        verbose_name_plural = "FAQs"  # Updated plural form
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]

    def __str__(self):
        return self.title if self.title else "Untitled FAQ"  # Handling None case

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int)
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

cart/views.py
from decimal import Decimal
from django.shortcuts import render
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from account.models import Image, User
from info.models import Info
from single.models import Single
from store.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)  # Ensure this line is correct
    product = get_object_or_404(Product, id=product_id)
    quantity = int(request.POST.get('quantity', 1))
    cart.add(product=product, quantity=quantity, override_quantity=True)  # This should work if add is defined
    return redirect('cart:cart_detail')



@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    image =Image.objects.all()
    user = User.objects.all()
    count = Decimal('0.02')  # Convert the float to Decimal
    discount = Decimal(cart.get_total_price()) * count
    delivery = Decimal('0.05') * Decimal(cart.get_total_price())
    subtotal = cart.get_total_price()
    total_price = subtotal - discount + delivery
    info = Info.objects.all()
    products = Product.objects.all()
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity': item['quantity'],
            'override': True
        })
        # Debugging line to check product id
    total_price = cart.get_total_price()
    return render(request, 'landing/cart.html', context ={
        'cart': cart,
        'user': user,
        'image': image,
        'total_price': total_price,
        "products": products,
        "info": info,
        'discount': discount,
        'delivery': delivery,
        'total_price': total_price,
        })

faq/views.py
from django.shortcuts import render

# Create your views here.

templates/landing/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<title>Liquor Store - Free Bootstrap 4 Template by Colorlib</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	{% include '../partials/_style.html' %}
</head>

<body>

	<div class="wrap">
		<div class="container">
			<div class="row">
				{% for i in info %}
				<div class="col-md-6 d-flex align-items-center">
					<p class="mb-0 phone pl-md-2">
						<a href="tel:{{ i.phone }}" class="mr-2"><span class="fa fa-phone mr-1"></span>{{ i.phone}}</a>
						<a href="https://t.me/{{ i.telegram }}"><span class="fa fa-paper-plane mr-1"></span>
							{{i.telegram }}<a>
					</p>
				</div>
				{% endfor %}
				<div class="col-md-6 d-flex justify-content-md-end">
					{% for i in info %}
					<div class="social-media mr-4">
						<p class="mb-0 d-flex">
							<a href="{{ i.facebook }}" class="d-flex align-items-center justify-content-center"><span
									class="fab fa-facebook"><i class="sr-only">Facebook</i></span></a>
							<a href="{{ i.discord }}" class="d-flex align-items-center justify-content-center"><span
									class="fab fa-discord"><i class="sr-only">discord</i></span></a>
							<a href="{{ i.instagram }}" class="d-flex align-items-center justify-content-center"><span
									class="fab fa-instagram"><i class="sr-only">Instagram</i></span></a>
						</p>
					</div>
					{% endfor %}
					<div class="reg">
						<p class="mb-0"><a href="register/" class="mr-2">Sign Up</a> <a href="login/">Log In</a></p>
					</div>
				</div>
			</div>
		</div>
	</div>

	{% include 'shared/nav.html' %}
	<!-- END nav -->
	{% for i in image %}
	<section class="hero-wrap hero-wrap-2" style="background-image: url('{% if i.image %}{{ i.image.url }}{% else %}{% static 'assets/img/no_image.png' %}{% endif %}')"
		data-stellar-background-ratio="0.5">
		{% endfor %}
		<div class="overlay"></div>
		<div class="container">
			<div class="row no-gutters slider-text align-items-end justify-content-center">
				<div class="col-md-9 ftco-animate mb-5 text-center">
					<p class="breadcrumbs mb-0"><span class="mr-2"><a href="index">Home <i
									class="fa fa-chevron-right"></i></a></span> <span>About us <i
								class="fa fa-chevron-right"></i></span></p>
					<h2 class="mb-0 bread">About Us</h2>
				</div>
			</div>
		</div>
	</section>

	{% include 'shared/supports.html' %}
	{% include 'shared/about.html' %}
	{% include 'shared/testimonial.html' %}

	<section class="ftco-counter ftco-section ftco-no-pt ftco-no-pb img bg-light" id="section-counter">
		<div class="container">
			<div class="row">
				{% for i in experiense %}
				<div class="col-md-3 justify-content-center counter-wrap ftco-animate">
					<div class="block-18 py-4 mb-4">
						<div class="text align-items-center">
							<strong class="number" data-number="{{ i.number }}">0</strong>
							<span>{{ i.title }}</span>
						</div>
					</div>
				</div>
				{% endfor %}
			</div>
		</div>
	</section>
	


	{% include 'shared/info.html' %}


	<!-- loader -->
	<div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px">
			<circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" />
			<circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
				stroke="#F96D00" />
		</svg></div>


	{% include '../partials/_scripts.html' %}
</body>

</html>

templates/landing/cart.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<title>Liquor Store - Free Bootstrap 4 Template by Colorlib</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	{% include '../partials/_style.html' %}
</head>

<body>

	<div class="wrap">
		<div class="container">
			<div class="row">
				{% for i in info %}
				<div class="col-md-6 d-flex align-items-center">
					<p class="mb-0 phone pl-md-2">
						<a href="tel:{{ i.phone }}" class="mr-2"><span class="fa fa-phone mr-1"></span>{{ i.phone}}</a>
						<a href="https://t.me/{{ i.telegram }}"><span class="fa fa-paper-plane mr-1"></span>
							{{i.telegram }}<a>
					</p>
				</div>
				{% endfor %}
				<div class="col-md-6 d-flex justify-content-md-end">
					{% for i in info %}
					<div class="social-media mr-4">
						<p class="mb-0 d-flex">
							<a href="{{ i.facebook }}" class="d-flex align-items-center justify-content-center"><span
									class="fab fa-facebook"><i class="sr-only">Facebook</i></span></a>
							<a href="{{ i.discord }}" class="d-flex align-items-center justify-content-center"><span
									class="fab fa-discord"><i class="sr-only">discord</i></span></a>
							<a href="{{ i.instagram }}" class="d-flex align-items-center justify-content-center"><span
									class="fab fa-instagram"><i class="sr-only">Instagram</i></span></a>
						</p>
					</div>
					{% endfor %}
					<div class="reg">
						<p class="mb-0"><a href="register/" class="mr-2">Sign Up</a> <a href="login/">Log In</a></p>
					</div>
				</div>
			</div>
		</div>
	</div>

	{% include 'shared/nav.html' %}
	<!-- END nav -->
	{% for i in image %}
	<section class="hero-wrap hero-wrap-2" style="background-image: url('{% if i.image %}{{ i.image.url }}{% else %}{% static 'assets/img/no_image.png' %}{% endif %}')"
		data-stellar-background-ratio="0.5">
		{% endfor %}
		<div class="overlay"></div>
		<div class="container">
			<div class="row no-gutters slider-text align-items-end justify-content-center">
				<div class="col-md-9 ftco-animate mb-5 text-center">
					<p class="breadcrumbs mb-0"><span class="mr-2"><a href="index">Home <i
									class="fa fa-chevron-right"></i></a></span> <span>Cart <i
								class="fa fa-chevron-right"></i></span></p>
					<h2 class="mb-0 bread">My Cart</h2>
				</div>
			</div>
		</div>
	</section>

	<section class="ftco-section">
		<div class="container">
			<div class="row">
				<div class="table-wrap">
					<table class="table">
						<thead class="thead-primary">
							<tr>
								<th>&nbsp;</th>
								<th>&nbsp;</th>
								<th>Product</th>
								<th>Price</th>
								<th>Quantity</th>
								<th>Total</th>
								<th>&nbsp;</th>
							</tr>
						</thead>
						<tbody>
							{% for item in cart %}
							<tr class="alert" role="alert">
								<td>
									<label class="checkbox-wrap checkbox-primary">
										<input type="checkbox" checked>
										<span class="checkmark"></span>
									</label>
								</td>
								<td>
									<div class="img" style="background-image: url('{% if item.product.image and item.product.image.url %}{{ item.product.image.url }}{% else %}{% static 'assets/img/no_image.png' %} {% endif %}')">
									</div>
								</td>
								<td>
									<div class="email">
										<span>{{ item.product.name }}</span>
										<span>{{ item.product.type }}</span>
									</div>
								</td>
								<td>${{ item.price }}</td>
								<td class="quantity">
									<div class="input-group">
										<form action="{% url 'cart:cart_add' item.product.id %}" method="post">
											{% csrf_token %}
											<input type="hidden" name="override" value="True">
											<input type="text" name="quantity"
												class="quantity form-control input-number" value="{{ item.quantity }}"
												min="1" max="100">
											<button type="submit" class="btn btn-outline-primary">Update</button>
										</form>

									</div>
								</td>
								<td>${{ item.total_price }}</td>
								<td>
									<form action="{% url 'cart:cart_remove' item.product.id %}" method="post">
										{% csrf_token %}
										<button type="submit" class="close" aria-label="Close">
											<span aria-hidden="true"><i class="fa fa-close">remove</i></span>
										</button>
									</form>
								</td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
			<a href="product">Continue shopping</a>

			<div class="row justify-content-end">
				<div class="col col-lg-5 col-md-6 mt-5 cart-wrap ftco-animate">
					<div class="cart-total mb-3">
						<h3>Cart Totals</h3>
						<p class="d-flex">
							<span>Subtotal</span>
							<span>${{ cart.get_total_price }}</span>
						</p>
						<p class="d-flex">
							<span>Delivery</span>
							<span>${{ delivery|floatformat:2 }}</span>
						</p>
						<p class="d-flex">
							<span>Discount</span>
							<span>${{ discount|floatformat:2 }}</span>
						</p>
						<hr>
						<p class="d-flex total-price">
							<span>Total</span>
							<span>${{ total_price|floatformat:2 }}</span>
						</p>
					</div>
					<p class="text-center"><a href="checkout" class="btn btn-primary py-3 px-4">Proceed to Checkout</a>
					</p>
				</div>
			</div>
		</div>
	</section>

	{% include 'shared/info.html' %}



	<!-- loader -->
	<div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px">
			<circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" />
			<circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
				stroke="#F96D00" />
		</svg></div>

	{% include '../partials/_scripts.html' %}

</body>

</html>

templates/landing/main.html
<div class="row justify-content-center">
  <div class="col-md-4">
    <a href="index" class="btn btn-primary d-block">back to page. <span class="fa fa-long-arrow-right"></span></a>
  </div>
</div>
<a href="https://github.com/Pybackender"><img
    src="https://colorlib.com/wp/wp-content/uploads/sites/2/colorlib-push-logo.png" alt="Colorlib logo"></a>
<h1 style="text-align:center;">Thank you for using our template!</h1>
<p style="text-align:center;">For more awesome templates please visit <strong><a
      href="https://github.com/Pybackender">Ops</a></strong>.</p>
<br>
<p style="text-align:center; color:red;"><strong>Copyright information for the template can't be altered/removed unless
    you purchase a license.</strong>


<p style="text-align:center;"><strong>If wanna template and website text me on telegram : hsn.ops ::<a
      href="https://t.me/hsn_ops">here</a></strong>.</p>
<p style="text-align:center;"><strong>Removing copyright information without the license will result in suspension of
    your hosting and/or domain name(s).</strong>

  <style>
    img {
      margin: 0 auto;
      display: block;
      margin-top: 20%;
    }
  </style>

templates/landing/product.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<title>Liquor Store - Free Bootstrap 4 Template by Colorlib</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	{% include '../partials/_style.html' %}
</head>

<body>

	<div class="wrap">
		<div class="container">
			<div class="row">
				{% for i in info %}
				<div class="col-md-6 d-flex align-items-center">
					<p class="mb-0 phone pl-md-2">
						<a href="tel:{{ i.phone }}" class="mr-2"><span class="fa fa-phone mr-1"></span>{{ i.phone}}</a>
						<a href="https://t.me/{{ i.telegram }}"><span class="fa fa-paper-plane mr-1"></span>
							{{i.telegram }}<a>
					</p>
				</div>
				{% endfor %}
				<div class="col-md-6 d-flex justify-content-md-end">
					{% for i in info %}
					<div class="social-media mr-4">
						<p class="mb-0 d-flex">
							<a href="{{ i.facebook }}" class="d-flex align-items-center justify-content-center"><span
									class="fab fa-facebook"><i class="sr-only">Facebook</i></span></a>
							<a href="{{ i.discord }}" class="d-flex align-items-center justify-content-center"><span
									class="fab fa-discord"><i class="sr-only">discord</i></span></a>
							<a href="{{ i.instagram }}" class="d-flex align-items-center justify-content-center"><span
									class="fab fa-instagram"><i class="sr-only">Instagram</i></span></a>
						</p>
					</div>
					{% endfor %}
					<div class="reg">
						<p class="mb-0"><a href="register/" class="mr-2">Sign Up</a> <a href="login/">Log In</a></p>
					</div>
				</div>
			</div>
		</div>
	</div>
	{% include 'shared/nav.html' %}
	<!-- END nav -->
	{% for i in image %}
	<section class="hero-wrap hero-wrap-2" style="background-image: url('{% if i.image %}{{ i.image.url }}{% else %}{% static 'assets/img/no_image.png' %}{% endif %}')"
		data-stellar-background-ratio="0.5">
		{% endfor %}
		<div class="overlay"></div>
		<div class="container">
			<div class="row no-gutters slider-text align-items-end justify-content-center">
				<div class="col-md-9 ftco-animate mb-5 text-center">
					<p class="breadcrumbs mb-0"><span class="mr-2"><a href="index">Home <i
									class="fa fa-chevron-right"></i></a></span> <span>Products <i
								class="fa fa-chevron-right"></i></span></p>
					<h2 class="mb-0 bread">Products</h2>
				</div>
			</div>
		</div>
	</section>
	<style>
        .resp-tabs-list {
            display: flex; /* Use Flexbox for horizontal alignment */
            list-style: none; /* Remove default list styling */
            padding: 0; /* Remove padding */
            margin: 0; /* Remove margin */
        }

        .resp-tab-item {
            margin-right: 20px; /* Space between items */
            padding: 10px 15px; /* Padding for items */
            cursor: pointer; /* Pointer cursor on hover */
            border: 1px solid transparent; /* Default border */
            border-radius: 5px; /* Rounded corners */
            transition: background-color 0.3s, border-color 0.3s; /* Smooth transitions */
        }

        .resp-tab-item:hover {
            background-color: #f0f0f0; /* Light background on hover */
            border-color: #007bff; /* Border color on hover */
        }

        .resp-tab-item.active {
            background-color: #007bff; /* Active tab background */
            color: white; /* Active tab text color */
            border-color: #007bff; /* Active border color */
        }
    </style>
	<section class="ftco-section">
		<div class="container">
			<div class="row">
				<div class="col-md-9">
					<div class="row mb-4">
						<div class="col-md-12 d-flex justify-content-between align-items-center">
							<ul class="resp-tabs-list">
								<li class="resp-tab-item" aria-controls="tab_item-0" role="tab">
									<a href="?">ALL</a>
								</li>
								{% for cat in categories %}
								<li class="resp-tab-item" aria-controls="tab_item-{{ forloop.counter }}" role="tab">
									<a href="?category={{ cat.id }}">{{ cat.title }}</a>
								</li>
								{% endfor %}
							</ul>
						</div>
					</div>
					<div class="row">
						{% for product in products %}
						<div class="col-md-4 d-flex">
							<div class="product ftco-animate">
								<div class="img d-flex align-items-center justify-content-center"
									 style="background-image: url('{% if product.image and product.image.url %}{{ product.image.url }}{% else %}{% static 'assets/img/no_image.png' %}{% endif %}')">
									<div class="desc">
										<p class="meta-prod d-flex">
											<a href="#" class="d-flex align-items-center justify-content-center"><span
													class="flaticon-shopping-bag"></span></a>
											<a href="#" class="d-flex align-items-center justify-content-center"><span
													class="flaticon-heart"></span></a>
											<a href="#" class="d-flex align-items-center justify-content-center"><span
													class="flaticon-visibility"></span></a>
										</p>
									</div>
								</div>
								<div class="text text-center">
									{% if product.on_sale %}
									<span class="sale">Sale</span>
									{% endif %}
									{% if product.best_seller %}
									<span class="seller">Best Seller</span>
									{% endif %}
									{% if product.new_arrival %}
									<span class="new">New Arrival</span>
									{% endif %}
									<span class="category">{{ product.name }}</span>
									<h2>{{ product.type }}</h2>
									<p class="mb-0"><span class="price price-sale">${{ product.last_price }}</span> <span
											class="price">${{ product.price }}</span>
									</p>
								</div>
								<form action="{% url 'cart:cart_add' product.id %}" method="post">
									{% csrf_token %}
									<input type="hidden" name="quantity" value="1">  <!-- Default quantity -->
									<p><button type="submit" class="btn btn-primary py-3 px-5 mr-2">Add to Cart</button></p>
								</form>
								
							</div>
						</div>
						{% endfor %}
					</div>
					

					<div class="row mt-5">
						<div class="col text-center">
							<div class="block-27">
								<ul>
									{% if products_has_previous %}
									<li><a href="?page={{ products_previous_page }}">&lt;</a></li>
									{% endif %}
									{% for num in products_page_range %}
									<li class="{% if num == products_number %}active{% endif %}"><a href="?page={{ num }}">{{ num }}</a></li>
									{% endfor %}
									{% if products_has_next %}
									<li><a href="?page={{ products_next_page }}">&gt;</a></li>
									{% endif %}
								</ul>
							</div>
						</div>
					</div>
					
				</div>
	
				<div class="col-md-3">
					<div class="sidebar-box ftco-animate">
						<div class="categories">
							<h3>Product Types</h3>
							{% for i in categories %}
							<ul class="p-0">
								<li><a href="#">{{ i.title }} <span class="fa fa-chevron-right"></span></a></li>
								
							</ul>
							{% endfor %}
						</div>
					</div>
	
					<div class="sidebar-box ftco-animate">
						<h3>Recent Blog</h3>
						{% for i in blog %}
						<div class="block-21 mb-4 d-flex">
							<a class="blog-img mr-4" style="background-image: url('{% if i.image %}{{ i.image.url }}{% else %}{% static 'assets/img/no_image.png' %}{% endif %}')"></a>
							<div class="text">
								<h3 class="heading"><a href="#">{{ i.content }}</a></h3>
								<div class="meta">
									<div><a href="#"><span class="fa fa-calendar"></span>{{ i.date }}</a></div>
									<div><a href="#"><span class="fa fa-comment"></span> 19</a></div>
								</div>
							</div>
						</div>
						{% endfor %}
					</div>
				</div>
			</div>
		</div>
	</section>	
	{% include 'shared/info.html' %}



	<!-- loader -->
	<div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px">
			<circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" />
			<circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
				stroke="#F96D00" />
		</svg></div>


	{% include '../partials/_scripts.html' %}

</body>

</html>